#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr %>%
#' @importFrom dplyr all_of
#' @importFrom dplyr arrange
#' @importFrom dplyr between
#' @importFrom dplyr case_when
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr one_of
#' @importFrom dplyr rename
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr ungroup
#' @importFrom factoextra get_pca_var
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 coord_flip
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_label
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_rug
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 geom_smooth
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_alpha
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_color_stepsn
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_x_reverse
#' @importFrom ggplot2 scale_y_reverse
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 xlim
#' @importFrom grDevices dev.off
#' @importFrom grDevices pdf
#' @importFrom grDevices png
#' @importFrom reshape2 melt
#' @importFrom rlang .data
#' @importFrom scales cut_short_scale
#' @importFrom scales label_number
#' @importFrom stats cor
#' @importFrom stats setNames
#' @importFrom stringr str_extract
#' @importFrom stringr str_replace
#' @importFrom tibble add_column
#' @importFrom utils read.table
#' @importFrom utils write.table
## usethis namespace: end
NULL
